### ISSUE TITLE
checkstyle failing to compile

### ISSUE THREAD

**Issue by TJesionowski** [jdee-emacs/jdee#155] opened 2018-08-23 18:44 UTC
### My Emacs version:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29
### My JDEE version (elpa package date):
20180819.1838
### My JDK version:
openjdk10
### My Operating System (Linux/OSX/Windows X/Other):
Linux
### Stacktrace (if applicable):
cd /home/tim/Documents/school/Auburn/COMP-2210/
/usr/lib/jvm/default/bin/java -classpath /home/tim/.emacs.d/lib/checkstyle/checkstyle-6.0.jar:/home/tim/.emacs.d/lib/checkstyle/antlr-2.7.7.jar:/home/tim/.emacs.d/lib/checkstyle/guava-18.0.jar:/home/tim/.emacs.d/lib/checkstyle/commons-beanutils-1.8.3.jar:/home/tim/.emacs.d/lib/checkstyle/commons-logging-1.2.jar:/home/tim/.emacs.d/lib/checkstyle/commons-cli-1.2.jar com.puppycrawl.tools.checkstyle.Main -c /home/tim/.emacs.d/etc/checkstyle.xml ./template.java

Error: Could not find or load main class com.puppycrawl.tools.checkstyle.Main
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.Main

Compilation exited abnormally with code 1 at Thu Aug 23 14:36:37
### How to reproduce (if applicable):
Load a sample java file into an emacs buffer. 
Through the JDEE drop-down menu, select Check Style
### Other info you consider could help to fix it:

[auburn.google_checks.xml.txt](https://github.com/jdee-emacs/jdee/files/2315754/auburn.google_checks.xml.txt)
[emacs.txt](https://github.com/jdee-emacs/jdee/files/2315756/emacs.txt)

**Comment by pwojnowski** [comment] 2018-08-26 08:15
This seems to be duplicate of #58 .

**Closed by pwojnowski** 2018-08-26 08:15 UTC
