### ISSUE TITLE
error installing jdee: "Selecting deleted buffer"

### ISSUE THREAD

**Issue by dgh1000** [jdee-emacs/jdee#148] opened 2018-06-03 20:43 UTC
On attempting to install jdee, got "error in package--load-file-for-activation: (error Selecting deleted buffer)" 

Note that emacs seems to think that jdee is installed at the end of this process, but I'm not sure if it's going to work correctly.

**Comment by pwojnowski** [comment] 2018-06-08 10:36
It seems like a duplicate of #95 .

**Closed by pwojnowski** 2018-06-08 10:36 UTC
Labels: duplicate
